// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArUEq0rr936zzRc3YPcVUWfm2HUcrwMs0',
    appId: '1:544764131000:web:28c78ca21fe8808c77664d',
    messagingSenderId: '544764131000',
    projectId: 'being-b54ef',
    authDomain: 'being-b54ef.firebaseapp.com',
    storageBucket: 'being-b54ef.appspot.com',
    measurementId: 'G-PJ9YXM3RCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8BlIFVW9LYsaqTw5-8Lt-uSlXAN2wno',
    appId: '1:544764131000:android:8bf79ec4628cfb3c77664d',
    messagingSenderId: '544764131000',
    projectId: 'being-b54ef',
    storageBucket: 'being-b54ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWymTMGT8iUF-rYMdWUvawzcdmIMAZkcI',
    appId: '1:544764131000:ios:768294223a761a8277664d',
    messagingSenderId: '544764131000',
    projectId: 'being-b54ef',
    storageBucket: 'being-b54ef.appspot.com',
    iosClientId: '544764131000-k3b8e366t6heepb90mehdbecnvs9f3s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.beingsocial',
  );
}
